config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  devise_for :users

  root 'welcome#index'
  get '/properties/:id/buy', to: 'properties#buy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commercial_unit.rb
class CommercialUnit < ApplicationRecord
  has_one :property, :as => :propertyable, :inverse_of => :propertyable
end

app/models/complex_building.rb
class ComplexBuilding < ApplicationRecord
  has_one :property, :as => :propertyable, :inverse_of => :propertyable
end

app/models/house.rb
class House < ApplicationRecord
  has_one :property, :as => :propertyable, :inverse_of => :propertyable
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user #owner user
  belongs_to :buyer, :class_name => 'User', foreign_key: :buyer_id,  optional: true

  belongs_to :propertyable, polymorphic: true

  after_save :send_message_to_users

  has_many_attached :images

  rails_admin do
    configure :propertyable do
      # configuration here
    end
  end


  def send_message_to_users
    VeryLongTaskJob.perform_later(self.user, self.buyer) if (self.buyer_id != nil)
  end 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :properties  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  before_action :authenticate_user!


  before_action :set_property, only: [:buy]

  
  def buy
    @property.buyer = current_user
    respond_to do |format|
      if @property.save
        format.html { redirect_to root_path, notice: 'Property was successfully created.' }
      else
        format.html { redirect_to root_path, error: 'Error on buy.' }
      end
    end
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:user_id, :address, :sqmt, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @properties = Property.where(buyer_id: nil)
  end

  def buy  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RhTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <!-- Begin Bootstrap Navbar -->
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Real House</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
 
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <% if user_signed_in? %>
              <li>
              <%= link_to('Logout', destroy_user_session_path, class: 'nav-link', method: :delete) %>        
              </li>
            <% else %>
              <li>
              <%= link_to('Login', new_user_session_path, class: 'nav-link') %>  
              </li>
            <% end %>
          </li>
          <%# <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    
    <!-- End Bootstrap Navbar -->
    
    <!-- Begin Bootstrap Tooltips -->
<%#  
    <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
      Tooltip on top
    </button>
    <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="right" title="Tooltip on right">
      Tooltip on right
    </button>
    <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="bottom" title="Tooltip on bottom">
      Tooltip on bottom
    </button>
    <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="left" title="Tooltip on left">
      Tooltip on left
    </button>
     %>
     <!-- End Bootstrap Tooltips -->
    <br>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :sqmt %>
    <%= form.number_field :sqmt %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Address</th>
      <th>Sqmt</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.user_id %></td>
        <td><%= property.address %></td>
        <td><%= property.sqmt %></td>
        <td><%= property.price %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @property.user_id %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @property.sqmt %>
</p>

<p>
  <strong>Price:</strong>
  <%= @property.price %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row row-centered">

      <% @properties.each_slice(3).to_a.each do |chunk| %>

        <% chunk.each do |property| %>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-centered">
             <div class="card card-primary">
                <div class="row padall">
                    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                        <span></span>
                        <%= image_tag(property.images[0], size: '80x105') if property.images.length > 0 %>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                        <div class="clearfix">
                            
                            <div class="float-xs-right">
                                <%= property.price%>$                                
                            </div>

                            <div class="float-xs-left">
                                <span class="fa fa-dollar icon"> <%= property.sqmt %></span>
                            </div>
                        </div>
                        <div>
                            <h4><span class="fa fa-map-marker icon"></span></h4>
                            <%= property.address %> <span class="fa fa-search icon float-xs-right"> </span>
                        </div>
                        <div class="pull-rigt">
                            <%= link_to '<button type="button" class="btn btn-success btn-sm">Buy</button>'.html_safe, "/properties/#{property.id}/buy" %>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        <% end %>

      <% end %>
  </div>
</div>